### ISSUE TITLE
Main Menu V1

### ISSUE THREAD

**Issue by VirtuosiMedia** [JunctionGate/junction-gate-issues#12]
# TODO

- [ ] New Game
- [ ] Resume Game (when paused)
- [ ] Exit Game
- [ ] About
- [ ] Version Number
- [ ] Build with HTML plugin
- [ ] 3D background
- [ ] Press ESC to pause game, bring up main menu

# Notes

This initial version will be simple and not include all functionality.

- No saves
- No settings
